apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-postgres-volume-claim
  labels:
    app: postgres
  annotations:
      description: "PostgreSQL database"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: linode-block-storage-retain