apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-server
  template:
    metadata:
      labels:
        app: telemetry-server
    spec:
      containers:
        - name: telemetry-server
          image: szbence/telemetryserver:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
      imagePullSecrets:
        - name: registry-pull-secret