apiVersion: v1
kind: Service
metadata:
  name: telemetry-server-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-nodebalancer-id: "542485"
    service.beta.kubernetes.io/linode-loadbalancer-preserve: "true"
spec:
  selector:
    app: telemetry-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
#  type: ClusterIP
