apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-server-app-config
data:
  application.properties: |
    #spring.profiles.active=develop,navdemo
    spring.profiles.active=develop
    
    server.port=8200
    
    #Postgresql connection params
    app.datasource.main.driver-class-name=org.postgresql.Driver
    app.datasource.main.jdbc-url=jdbc:postgresql://postgres:5432/tms
    app.datasource.main.username=tmsuser
    app.datasource.main.password=tmsuser
    app.datasource.main.pool-size=30
    
    #Rabbitmq connection params
    spring.rabbitmq.host=rabbitmq-0.rabbitmq.rabbits.svc.cluster.local
    spring.rabbitmq.port=5672
    spring.rabbitmq.virtual-host=/
    spring.rabbitmq.username=guest
    spring.rabbitmq.password=guest
      
    spring.rabbitmq.publisher-returns=true
    spring.rabbitmq.template.mandatory=true
    spring.rabbitmq.listener.simple.retry.enabled=true
    
    #Signiture verification
    package.signer.public.key=/opt/telemetryserver/conf/pub-key.pem
    package.verify.signature=false
    
    #Subsystem url value mapping to address
    subsystem.mapping={'afe': 'http://localhost:8200', 'fcu': 'http://localhost:8300'}
    
    #Headers should be included from the proxy request. Every list element is a regex expression
    included.proxy.headers={'^X-Forwarded-For$','^Forwarded$','^Content-Type$', '^Accept$', '^Accept-Charset$', '^Accept-Datetime$', '^Accept-Language$', '^Content-MD5$', '^Cookie$', '^Date$', '^X-Client-Cert$', '^Client-Cert$', '^X-Client-Cert-Chain$', '^Client-Cert-Chain$' }
    
    #Headers should be included from the proxy response. Every list element is a regex expression
    included.proxy.response.headers={'^Content-Type$', '^Cache-Control$', '^Content-MD5$', '^Expires$', '^Last-Modified$', '^Set-Cookie$', '^Content-Disposition$' }
    
    #Connection timeout
    server.tomcat.connection-timeout=60s
    spring.mvc.async.request-timeout=600s
    
    #Max file size and max request size
    spring.servlet.multipart.max-file-size=5MB
    spring.servlet.multipart.max-request-size=5MB
    
    #Package element removal cron
    package.element.delete.cron=15 0 0 * * *
    
    #Statistic
    statistic.device.cron=0 0 * * * *
    statistic.clean.up.cron=10 0 0 * * 1
    
    # Given in hours
    statistic.cleanup.min.turningpoint=24
    statistic.cleanup.hour.turningpoint=720
    statistic.cleanup.day.turningpoint=8760
    statistic.cleanup.week.turningpoint=43800

  pub-key.pem: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsMTmbMflxKh5oFqz50Yb
    Mz9E0xFbqoXiiUrphKKU7ZD5WLUHloS26TP3G1O4K78Zc8FhaDoUj33QmTYku3ic
    LhJcTGOXfRCAuNh1NwhAo+ywv1zVjlMkUqmEdyfncOYkKYzuBngAbKmEV1U5D230
    BItA0/epY1pHwiHJDyBK4KCUySJqho8WyyYW7X/NU6r8ej1+WB/G7P6aRxBOWFpK
    CUJTXk+xXOP+h/+Y2CvY3MSvJI1IDaeNBf2Z3Taep6p0Ma3GWFbx0xHF464MN2oQ
    BLBQPYUPyLo3zmtz03LjH6WeKgNFVyCbuV5FjEB6DH2U27pHVStaKbOTwzvzwRGz
    4NgqypBEZJNU1gVRkkOPG8cP8uAAPnM/sEhrhPkMjBkmys9SRJTEetGfG67akoqJ
    25ExEJ8tzP9vaEK8A80wlbdKiHT8LxxBDfxCqnfK3fAfbkYW0TF5uyy3VwhJojtm
    Utv+H1Kgo3+Dhcfavneda++8VqnaNlPMrncxpMD+S8vnwzOy+pSiZgQWsZFJ97YZ
    457Nb+BpSOjD900+JSeP5wNrJcNwjhZn6XF5mJcyK5JlA8SC9n0KypZr/2nN6f/f
    /DJGxMPYWcptAkdqSOThd0LBYcw2YKghOql73XvdvdDwTAnWXa8Z/GbFeuBR0TI+
    /cBiGJNERnIznikC770M7E0CAwEAAQ==
    -----END PUBLIC KEY-----
