apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-server
  template:
    metadata:
      labels:
        app: telemetry-server
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: telemetry-server
          image: szbence/telemetryserver:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-override-volume
              mountPath: /opt/telemetryserver/conf/application.properties
              subPath: custom_path
      volumes:
        - name: config-override-volume
          configMap:
            name: telemetry-server-app-config
            items:
              - key: application.properties
                path: custom_path